### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by evenstensberg**
Added import plugin so people can use `npm run validate` straight away

### CODE REVIEW

**Comment by evenstensberg** [comment]
--FWIW, It's just a utility, but a nice one 🙈

**Comment by kentcdodds** [comment]
Ah! Yes, so when you come the repo and install dependencies, do you get an error when trying to run the validate script?

**Comment by evenstensberg** [comment]
Yea, but test it yourself first, since I had an additional import statement, of which I commented out, could be that as well! Regardless, running eslint after validate warned that it should be installed, so its a nice thing to have anyway. 

Also, at Lesson 6 ( egghead) you should have introduced `--only=dev` as a flagg instead when installing as a dep, since it is new for webpack 2.0, as you probably already know 😄

**Comment by kentcdodds** [comment]
Ah, so yeah, we don't need to use the imports plugin because we're using the `kentcdodds/es-next` module for our eslint config. Now if instead we did:

``` javascript
extends: ['kentcdodds/es-next', 'kentcdodds/import', 'kentcdodds/webpack']
```

(which is what we probably should do), then we'd need to install:

``` console
npm install --save-dev eslint-plugin-import eslint-import-resolver-webpack
```

I may do this later. But for now we'll leave it as-is. Thanks!

**Pull request closed without merging**
